version: "2"

services:
  web:
    image: "johannhartmann/noderedis"
    ports:
      - 80
    labels:
      - "interlock.hostname=guestbook"
      - "interlock.domain=local"
    links:
      - "redis:redis"
    volumes:
      - .:/code
    environment:
      - "constraint:node==node02"
    expose:
      - 80
    hostname: "guestbook"
    domainname: "local"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - /data
    environment:
      - "constraint:node==redis"

networks:
   default:
    external:
      name: "mynet"
