version: "2"

services:
  web:
    image: "johannhartmann/noderedis:latest"
    ports:
      - 80
    labels:
      - "interlock.hostname=guestbook"
      - "interlock.domain=mayflower.de"
    volumes:
      - .:/code
    networks:
      - "default"
    depends_on:
      - redis
    extra_hosts:
      - "redis:192.168.33.250"
    expose:
      - 80
    hostname: "guestbook"
    domainname: "mayflower.de"
    environment:
      - "constraint:node==node*"

  redis:
    image: "johannhartmann/redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - /data
    networks:
      - "default"
    environment:
      - "constraint:node==redis"

networks:
   default:
    external:
      name: "mynet"
